name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Установка компилятора
      run: sudo apt-get install g++
    - name: Компиляция проекта
      run: g++ -o infix-postfix-solve src/infix-postfix-solve/infix-postfix-solve.cpp
    - name: Запуск программы
      run: ./infix-postfix-solve
